Repository joshsoftware/intranet-mobile, pull requests merged in 2023-06, with the labels that each got.

#47 Bug: 39 Form Values does on reset after form submission
  src/app/components/pickers/pickerSelect.tsx
  src/app/screens/TimesheetScreen/component/timesheetForm.tsx
  src/app/screens/TimesheetScreen/view/createTimesheet.tsx
Labels: bug

#53 Typo fix leave filter property from "end" to "to"
  src/app/screens/LeaveScreen/ManagementLeaveScreen/index.tsx
Labels: bug

#57 Social Media Icons Updated
  src/app/constant/icons.ts
  src/app/screens/ProfileScreen/component/IconButton.tsx
  src/app/screens/ProfileScreen/interface/publicProfile.ts
  src/app/screens/ProfileScreen/tabs/PublicProfile.tsx
  src/assets/svg/blog.svg
  src/assets/svg/twitter.svg
  src/index.d.ts
Labels: Do Not Merge, API Dependency

#68 Drawer close and swipe disable
  src/app/components/DrawerContent.tsx
  src/app/navigation/DrawerNavigation.tsx
Labels: bug

#67 Feature/54 home screen calendar
  package-lock.json
  package.json
  src/app/components/typography/index.tsx
  src/app/constant/apiRoutes.ts
  src/app/constant/colors.ts
  src/app/navigation/MainNavigator.tsx
  src/app/screens/HomeScreen/Calendar/Label.tsx
  src/app/screens/HomeScreen/Calendar/index.tsx
  src/app/screens/HomeScreen/dashboard.hooks.ts
  src/app/screens/HomeScreen/index.tsx
  src/app/services/home/index.ts
  src/app/services/home/types.ts
Labels: Do Not Merge
